# Generated by Django 4.2.5 on 2024-03-23 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='delivered',
            field=models.BooleanField(default=False),
        ),
    ]
