# Generated by Django 4.2.5 on 2024-03-07 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0002_remove_topic_category_remove_topic_subject_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactLeads',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_updated', models.DateTimeField(auto_now_add=True, null=True)),
                ('name', models.CharField(max_length=120)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('RESOLVED', 'Resolved'), ('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('SPAM', 'Spam')], default='PENDING', max_length=20)),
            ],
            options={
                'ordering': ['name', 'date_created', 'date_updated'],
                'abstract': False,
            },
        ),
    ]
