# Generated by Django 4.2.5 on 2024-03-15 18:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_remove_teacher_subtopic_topiccontent'),
        ('admins', '0004_topic_subtopic'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='added_by',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updated_by_teacher', to='user.topiccontent'),
        ),
        migrations.AddField(
            model_name='topic',
            name='status',
            field=models.CharField(blank=True, choices=[('unverify', 'Unverify'), ('verify', 'Verify')], default='unverify', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='topic',
            name='topic_content',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='content_from_teacher', to='user.topiccontent'),
        ),
        migrations.AddField(
            model_name='topic',
            name='updated_by',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
