# Generated by Django 4.2.5 on 2024-03-16 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0005_topic_added_by_topic_status_topic_topic_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name='Subtopic',
        ),
    ]
