# Generated by Django 4.2.5 on 2024-03-17 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0006_alter_topic_name_delete_subtopic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='added_by',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='status',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='topic_content',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='updated_by',
        ),
    ]
