# Generated by Django 4.2.5 on 2024-03-19 02:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_topiccontent_options_remove_topiccontent_name'),
        ('admins', '0008_topic_topic_content_alter_topic_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='topic_content',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='content_from_teacher', to='user.topiccontent'),
        ),
    ]
