# Generated by Django 4.2.5 on 2024-03-20 02:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0009_alter_topic_topic_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='topic_content',
        ),
    ]
