# Generated by Django 4.2.5 on 2024-03-20 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0010_remove_topic_topic_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
