# Generated by Django 4.2.5 on 2024-03-20 03:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('admins', '0011_alter_topic_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='assign_to',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_topics', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
