# Generated by Django 4.2.5 on 2024-03-14 07:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srm', '0043_alter_advertisment_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisment',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 14, 7, 38, 56, 547323, tzinfo=datetime.timezone.utc)),
        ),
    ]
