# Generated by Django 4.2.5 on 2024-03-17 16:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srm', '0055_alter_advertisment_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisment',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 17, 16, 3, 0, 288990, tzinfo=datetime.timezone.utc)),
        ),
    ]
