# Generated by Django 4.2.5 on 2024-03-23 04:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srm', '0073_alter_advertisment_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisment',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 23, 4, 41, 56, 632602, tzinfo=datetime.timezone.utc)),
        ),
    ]
