# Generated by Django 4.2.5 on 2024-03-15 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_remove_teacher_subtopic_topiccontent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='topiccontent',
            options={},
        ),
        migrations.RemoveField(
            model_name='topiccontent',
            name='name',
        ),
    ]
