# Generated by Django 4.2.5 on 2024-03-20 02:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0010_remove_topic_topic_content'),
        ('user', '0004_alter_topiccontent_options_remove_topiccontent_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topiccontent',
            name='category',
        ),
        migrations.RemoveField(
            model_name='topiccontent',
            name='subject',
        ),
        migrations.AlterField(
            model_name='topiccontent',
            name='topic',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='admins.topic'),
        ),
    ]
